### ISSUE TITLE
Some clarifications

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [ralphhanna/bpmn-server#53]
**_Using 1.3.6_**

### Clarification 1:

This is related to the **Issue scenario 2** mentioned in #51.

I trying to use the `messageMatchingKey` to handle **signal** events targeting a specific instance with the examples `test-throw` and `test-catch`.

I tried these three below listener options for the end signal event on `test-catch` process to target the specific instances of `test-throw`  processes.

```xml
<camunda:executionListener event="end">
          <camunda:script scriptFormat="JavaScript">this.context.messageMatchingKey={'data.caseId': this.token.data.caseId };</camunda:script>
</camunda:executionListener>
```
```xml
<camunda:executionListener event="end">
          <camunda:script scriptFormat="JavaScript">this.messageMatchingKey={'data.caseId': this.token.data.caseId };</camunda:script>
</camunda:executionListener>
```
```xml
<camunda:executionListener event="end">
          <camunda:script scriptFormat="JavaScript">data.caseId= input.caseId;</camunda:script>
</camunda:executionListener>
```
But I can't get it to work!
I think I am missing something basic but couldn't figure it out. Sorry!
If you could kindly clarify how to handle that, it would be great.

### Clarification 2:

When to use the `start` and `end` on listener scripts?

```xml
<bpmn2:extensionElements>
     <camunda:executionListener event="start">
           <camunda:script scriptFormat="JavaScript">
           </camunda:script>
     </camunda:executionListener>
</bpmn2:extensionElements>
```
```xml
<bpmn2:extensionElements>
     <camunda:executionListener event="end">
           <camunda:script scriptFormat="JavaScript">
           </camunda:script>
     </camunda:executionListener>
</bpmn2:extensionElements>
```

And what's the difference b/w them in terms of their execution?

On a related note, where may I find the documentation of properties panel and it's configuration?

Thank you!

**Comment by ralphhanna** [comment]
# Clarification 2
- 'start' event fires before the step executes
- 'end' event fires after the step executes
# Clarification 1
The following worked for me:
for 'test-catch' Throw Signal Event add a the start event: (before the signal fires)
   this.log("this is the start listener");
   this.context.messageMatchingKey={caseId:9999};
   this.log(this.context.messageMatchingKey);
This sets the key to a strange number so the test-throw will not catch it (opposite of what is required)

![image](https://user-images.githubusercontent.com/11893416/188684054-035d8195-9394-4198-ac49-4215458a82b0.png)

as a result the test-throw couldn't catch it and remained not complete.

I am working on a better example, but if you a complete example of multiple instances that would be great

**Comment by ralphhanna** [comment]
I have created a new test scenario, tested under 1.3.7
as follows:
* t-throw-signals - throws 3 signals 101,102, 103 (with matching key of client id)

![image](https://user-images.githubusercontent.com/11893416/188775027-4c794660-ab68-48fb-acc1-b70bd18beb0a.png)


* t-catch-signals1 - catches 101 and 102 but not 103 since it does not have clientId
![image](https://user-images.githubusercontent.com/11893416/188774622-54b628cb-c2b3-4c88-ab77-3ce33264c8bf.png)

* t-catch-signals2 - catches 101,102 and 103 since it has clientId of 101
![image](https://user-images.githubusercontent.com/11893416/188774684-cb00ace9-f9a7-4424-9241-12f5fb864998.png)

Results :
![image](https://user-images.githubusercontent.com/11893416/188774516-5dda7435-6127-4e5e-88c6-924913f27e98.png)

Please not that the trick here is that MessageMatchingKey works only with instances not processes.

Please send me your models if you need any help with them, I can test them for you.

**Comment by ralphhanna** [comment]
Please update to Release 1.3.7 to test the above

**Comment by MaheshkumarSundaram** [comment]
Thank you. I'll send you my models if any concerns.

**Comment by MaheshkumarSundaram** [comment]
Hi @ralphhanna,

It seems you have missed committing the updated BPMN process files for `t-catch-signals`, `t-catch-signals2` & `t-throw-signals`.
Could you look into this please!
